name: E2E Tests + Report

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        env: [dev, prod]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Start API
        run: |
          docker run -d -p 3000:3000 ghcr.io/danielsilva-loanpro/sdet-interview-challenge:latest
          sleep 5

      - name: Wait for API
        run: |
          until curl -s http://localhost:3000/${{ matrix.env }}/users > /dev/null; do
            sleep 2
          done

      - name: Run tests
        run: |
          if [ "${{ matrix.env }}" = "dev" ]; then
            npx playwright test src/tests/users.dev.spec.ts
          else
            npx playwright test src/tests/users.prod.spec.ts
          fi
        env:
          BASE_URL: http://localhost:3000

      - name: Upload report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report-${{ matrix.env }}
          path: playwright-report/

  deploy-report:
    needs: e2e
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          path: reports

      - name: Merge reports + create index
        run: |
            mkdir public

            cp -r reports/report-dev/playwright-report/* public/ || true

            mkdir -p public/prod
            cp -r reports/report-prod/playwright-report/* public/prod/ || true

            cat <<EOF > public/index.html
            <html>
            <head>
                <title>Playwright Reports</title>
                <style>
                body { font-family: Arial; text-align: center; padding: 50px; }
                a { display: block; margin: 20px; font-size: 20px; text-decoration: none; }
                </style>
            </head>
            <body>
                <h1>Test Reports</h1>
                <a href="./index.html">DEV Report</a>
                <a href="./prod/index.html">PROD Report</a>
            </body>
            </html>
            EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4